Update action.yml (#33)

diff --git a/setup-repo/action.yml b/setup-repo/action.yml
--- a/setup-repo/action.yml
+++ b/setup-repo/action.yml
@@ -53,9 +53,22 @@ runs:
       with:
         fetch-tags: true
         path: ${{ inputs.working_directory }}
-        ref: ${{ inputs.short_git_sha || '' }}
+        ref: ${{ inputs.ref || '' }}
         repository: ${{ inputs.repo }}
         token: ${{ inputs.personal_access_token }}
+
+    - name: Check if the correct ref is checked out
+      run: |
+        input_ref=${{ inputs.ref || '' }}
+
+        [ -n "$input_ref" ] && exit 0
+
+        if [[ "$(git rev-parse HEAD)" != "$(git rev-parse $input_ref)" ]]; then
+          echo "Error: Incorrect ref checked out."
+          exit 1
+        fi
+      shell: bash
+      working-directory: ${{ inputs.working_directory }}
 
     - name: Gather github sha
       run: |
